//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Unity.Precompiler.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity
{
    using Microsoft.Practices.ObjectBuilder2;
    using Microsoft.Practices.Unity;
    using System;
    using System.Collections;
    using System.Collections.Generic;

    public partial class Precompiled : UnityContainerExtension, 
                                       IBuildPlanCreatorPolicy
    {
        private IBuildPlanCreatorPolicy _factory;

        /// <summary>
        /// Extension Initialization
        /// </summary>
        protected override void Initialize()
        {
            _factory = (IBuildPlanCreatorPolicy)Context.Policies
                .Get(typeof(IBuildPlanCreatorPolicy), null, false, out var _);

            Context.Policies.SetDefault<IBuildPlanCreatorPolicy>(this);
        }

        /// <summary>
        /// <see cref="IBuildPlanCreatorPolicy"/> interface implementation
        /// </summary>
        public IBuildPlanPolicy CreatePlan(IBuilderContext context, NamedTypeBuildKey buildKey) 
            => TryGet(buildKey.Type, buildKey.Name, null, out var policy)
            ? (IBuildPlanPolicy)policy
            : _factory.CreatePlan(context, buildKey);
    }
}