//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Unity.Precompiler.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using Unity.Builder;
    using Unity.Extension;
    using Unity.Policy;
    using Unity.Resolution;

    public partial class Precompiled : UnityContainerExtension,
                                       IUnityContainerExtensionConfigurator
    {
        private ResolveDelegateFactory _factory;

        /// <summary>
        /// Extension Initialization
        /// </summary>
        protected override void Initialize()
        {
            _factory = (ResolveDelegateFactory)Context.Policies
                .Get(null, null, typeof(ResolveDelegateFactory));

            Context.Policies
                .Set(null, null, typeof(ResolveDelegateFactory), (ResolveDelegateFactory)Factory);
        }

        private ResolveDelegate<BuilderContext> Factory(ref BuilderContext context) 
            => TryGet(context.Type, context.Name, null, out var policy)
            ? (ResolveDelegate<BuilderContext>)policy
            : _factory.Invoke(ref context);
    }
}