//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Unity.Precompiler.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity
{
    using System;

    public partial class Precompiled
    {
        private bool TryGet(Type type, string name, object[] args, out object policy)
        {
            policy = null;

            return false;
        }
    }
}